# Generated by Django 5.2 on 2025-04-25 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='disciplina',
            options={'verbose_name_plural': 'Disciplinas'},
        ),
        migrations.AlterModelOptions(
            name='professor',
            options={'verbose_name_plural': 'Professores'},
        ),
        migrations.AlterModelOptions(
            name='reservaambiente',
            options={'verbose_name_plural': 'Reservas de Ambiente'},
        ),
    ]
