# Generated by Django 5.2 on 2025-05-06 11:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_professor_ni'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='telefone',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='O telefone deve seguir o formato 12 12345-6789', regex='^\\d{2} \\d{5}-\\d{4}$')]),
        ),
    ]
