# Generated by Django 5.2 on 2025-05-06 12:07

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_professor_telefone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disciplina',
            name='professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disciplinas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reservaambiente',
            name='professor_responsavel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usuario',
            name='dt_contratacao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='dt_nascimento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='ni',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='O número de identificação deve seguir o formato 12345/67', regex='^\\d{5}/\\d{2}$')]),
        ),
        migrations.AddField(
            model_name='usuario',
            name='telefone',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='O telefone deve seguir o formato 12 12345-6789', regex='^\\d{2} \\d{5}-\\d{4}$')]),
        ),
        migrations.DeleteModel(
            name='Professor',
        ),
    ]
