# Generated by Django 5.2 on 2025-05-06 12:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_disciplina_professor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservaambiente',
            name='dt_inicio',
            field=models.DateTimeField(validators=[django.core.validators.RegexValidator(message='A data deve seguir o formato dd/mm/aaaa', regex='^\\d{2}/\\d{2}/\\d{4}$')]),
        ),
        migrations.AlterField(
            model_name='reservaambiente',
            name='dt_termino',
            field=models.DateTimeField(validators=[django.core.validators.RegexValidator(message='A hora deve seguir o formato hh:mm', regex='^\\d{2}:\\d{2}$')]),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='dt_contratacao',
            field=models.DateField(blank=True, null=True, validators=[django.core.validators.RegexValidator(message='A data deve seguir o formato dd/mm/aaaa', regex='^\\d{2}/\\d{2}/\\d{4}$')]),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='dt_nascimento',
            field=models.DateField(blank=True, null=True, validators=[django.core.validators.RegexValidator(message='A data deve seguir o formato dd/mm/aaaa', regex='^\\d{2}/\\d{2}/\\d{4}$')]),
        ),
    ]
