# Generated by Django 5.2 on 2025-05-06 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_reservaambiente_dt_inicio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservaambiente',
            name='dt_inicio',
        ),
        migrations.RemoveField(
            model_name='reservaambiente',
            name='dt_termino',
        ),
    ]
