# Generated by Django 5.2 on 2025-05-06 13:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_reservaambiente_dt_inicio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservaambiente',
            name='dt_inicio',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='reservaambiente',
            name='dt_termino',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='dt_contratacao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='dt_nascimento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
