# Generated by Django 5.2 on 2025-05-06 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_reservaambiente_dt_inicio_reservaambiente_dt_termino_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservaambiente',
            name='dt_inicio',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='reservaambiente',
            name='dt_termino',
            field=models.DateTimeField(),
        ),
    ]
