# Generated by Django 5.2 on 2025-05-15 11:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_reservaambiente_dt_inicio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='ni',
            field=models.CharField(blank=True, max_length=8, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='O número de identificação deve seguir o formato 12345/67', regex='^\\d{5}/\\d{2}$')]),
        ),
    ]
