# Generated by Django 5.2 on 2025-05-16 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_rename_professor_disciplina_professor_responsval'),
    ]

    operations = [
        migrations.RenameField(
            model_name='disciplina',
            old_name='professor_responsval',
            new_name='professor_disciplina',
        ),
    ]
