# Generated by Django 5.2 on 2025-05-16 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_rename_professor_responsval_disciplina_professor_disciplina'),
    ]

    operations = [
        migrations.RenameField(
            model_name='disciplina',
            old_name='professor_disciplina',
            new_name='professor',
        ),
    ]
