# Generated by Django 5.2 on 2025-05-22 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_rename_professor_disciplina_disciplina_professor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='disciplina',
            old_name='professor',
            new_name='professor_responsavel',
        ),
    ]
